### ISSUE TITLE
Updfating Library

### ISSUE THREAD

**Issue by hokuto123456789** [delhatch/PiPod_ePaper#2]
hello. Please let me know because I can't get it right while I'm creating it.

1. Put MP3 files in Music folder
2. Menu Settings Select Update Library

I get an error like the one below and can't return to the menu.
Is there a solution?

![image](https://github.com/user-attachments/assets/e4df2dc2-c6b0-4fbf-98cc-d71f50d3f94e)

pi@raspberrypi:~/PiPod_ePaper/Software $ python3 main.py
Traceback (most recent call last):
  File "/home/pi/PiPod_ePaper/Software/main.py", line 142, in <module>
    music.updateLibrary()  # Re-create the info.csv file
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PiPod_ePaper/Software/playback.py", line 283, in updateLibrary
    stringTitle = newtitle[0].lstrip()
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'newtitle' where it is not associated with a value

**Comment by delhatch** [comment]
I can think of a few things to do:
* look at the info.csv file. It should contain a CSV list of titles, artists, etc...
* look at the playback.py code near the end (lines 330-334). There are some debug print lines you can un-comment to see what the code sees as it parses the files in the Music directory.
* Make sure either your music files have filenames like "James Taylor - Steamroller.mp3" AND that the UseMeta is set to False  (line 15), OR
* Set UseMeta to True. Once set to True, info.csv will be built/made/created using the metadata contained in the music file itself, ignoring the file names.

My guess is that the lines 330-334 will print out which music file(s) are causing a problem during the creation of info.csv.

If all else fails, you can modify the parser to extract the music file metadata from whatever system/method your filenames use.

**Comment by hokuto123456789** [comment]
Thank you. If you set the file name of the music file to something like "James Taylor - Steamroller.mp3", it will be recognized. I couldn't find this rule.
・ I was able to play music, but it is full of noise, so I will try to find the cause.
When D2 is removed, there is noise, but D2parts are arranged and reattached.

**Comment by hokuto123456789** [comment]
I'm talking about D2, not D1, but it always makes noise whether it's USB powered or battery powered. Is there a solution?
Especially when running on battery power, the noise gets louder and you can't hear the music.
Bluetooth and Wi-Fi are also turned off.

I created two boards, and both have the same symptoms.
